version: '3.6'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8036:80"
    environment:
      PMA_HOST: db
      PMA_USER: db
      PMA_PASSWORD: db
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
